#!/usr/bin/env python3
"""
Keyword extraction using vLLM and Qwen2.5-7B-Instruct model
Extract 20 most important keywords from long underscore-connected tags
"""

import json
import re
from typing import Dict, List
from vllm import LLM, SamplingParams
import argparse
from tqdm import tqdm

class KeywordExtractor:
    def __init__(self, model_name: str = "Qwen/Qwen2.5-7B-Instruct", tensor_parallel_size: int = 4):
        """
        Initialize keyword extractor
        
        Args:
            model_name: Model name, default uses Qwen2.5-7B-Instruct
            tensor_parallel_size: Tensor parallel size, default is 4 (suitable for 4-card A100)
        """
        print(f"Loading model: {model_name}")
        print(f"Using {tensor_parallel_size} GPUs for tensor parallelism")
        self.llm = LLM(
            model=model_name,
            tensor_parallel_size=tensor_parallel_size,  # 4-card A100 parallel
            gpu_memory_utilization=0.85,  # A100 has sufficient memory, can set higher
            max_model_len=16384,  # A100 supports longer sequences, increased to 16K
            trust_remote_code=True,  # Support Qwen model
            enforce_eager=False,  # Enable CUDA graph optimization
        )
        
        # Set sampling parameters - optimized for 4-card A100
        self.sampling_params = SamplingParams(
            temperature=0.4,  # Increase temperature for diversity, avoid repetition
            top_p=0.9,
            max_tokens=800,  # Increase token count, give model more analysis space
            stop=["</s>", "\n\n"],
            # A100 optimization parameters
            skip_special_tokens=True,
            repetition_penalty=1.1,  # Add repetition penalty
        )
        
        print("Model loading completed!")

    def create_prompt(self, tag_text: str) -> str:
        """
        Create keyword extraction prompt
        
        Args:
            tag_text: Input tag text (long string connected by underscores)
        
        Returns:
            Formatted prompt
        """
        prompt = f"""You are an expert at analyzing and extracting key concepts from text. Given a long text that consists of multiple topics and concepts joined by underscores, your task is to identify and extract exactly 20 of the most important and representative keywords or key phrases.

Input text (topics joined by underscores):
{tag_text}

Instructions:
1. Analyze the entire text and identify the most important concepts, themes, and topics
2. Extract exactly 20 diverse keywords/phrases that best represent the core themes
3. Prioritize more general and important concepts over very specific details
4. Ensure keywords are diverse and cover different aspects of the content - NO DUPLICATES
5. Keywords can be single words or short phrases (1-4 words each)
6. Within each keyword/phrase, use proper spacing and hyphens as needed (e.g., "World War II", "machine learning", "climate change")
7. Only use underscores to separate different keywords, NOT within keywords
8. Avoid repetition - each keyword should be unique and distinct
9. Do not include explanations, just provide the keywords joined by underscores

Output format: keyword1_keyword2_keyword3_..._keyword20

Example: "World War II_machine learning_climate change_artificial intelligence_economic policy_social media_renewable energy_space exploration_medical research_cultural heritage_international relations_technological innovation_environmental protection_educational reform_financial markets_urban planning_scientific discovery_digital transformation_sustainable development_global cooperation"

Keywords:"""
        
        return prompt

    def extract_keywords_batch(self, tag_texts: List[str]) -> List[str]:
        """
        Extract keywords in batch
        
        Args:
            tag_texts: List of tag texts
            
        Returns:
            List of extracted keywords
        """
        prompts = [self.create_prompt(text) for text in tag_texts]
        
        print(f"Processing {len(prompts)} tags...")
        outputs = self.llm.generate(prompts, self.sampling_params)
        
        results = []
        for output in outputs:
            generated_text = output.outputs[0].text.strip()
            # Clean output, ensure correct format
            cleaned_keywords = self.clean_keywords(generated_text)
            results.append(cleaned_keywords)
            
        return results

    def clean_keywords(self, generated_text: str) -> str:
        """
        Clean generated keyword text
        
        Args:
            generated_text: Raw text generated by model
            
        Returns:
            Cleaned keyword string
        """
        # Remove possible prefixes and suffixes
        text = generated_text.strip()
        
        # If contains newlines, only take the first line
        if '\n' in text:
            text = text.split('\n')[0]
        
        # Remove quotes and other unnecessary punctuation, but keep spaces, hyphens and underscores
        text = re.sub(r'["""''`]', '', text)
        text = re.sub(r'[^\w\s_-]', '', text)
        
        # Split keywords by underscores
        keywords = [kw.strip() for kw in text.split('_') if kw.strip()]
        
        # Clean extra spaces within each keyword
        cleaned_keywords = []
        for kw in keywords:
            # Normalize internal spaces
            cleaned_kw = re.sub(r'\s+', ' ', kw.strip())
            if cleaned_kw and cleaned_kw not in cleaned_keywords:  # Remove duplicates
                cleaned_keywords.append(cleaned_kw)
        
        # Limit to 20 keywords
        cleaned_keywords = cleaned_keywords[:20]
        
        return '_'.join(cleaned_keywords)

    def process_json_file(self, input_file: str, output_file: str, batch_size: int = 32):
        """
        Process all tags in JSON file
        
        Args:
            input_file: Input JSON file path
            output_file: Output JSON file path
            batch_size: Batch processing size
        """
        print(f"Loading JSON file: {input_file}")
        
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        print(f"Found {len(data)} tag items")
        
        # Prepare batch processing
        keys = list(data.keys())
        values = list(data.values())
        result_data = {}
        
        # Process in batches
        for i in tqdm(range(0, len(values), batch_size), desc="Processing batches"):
            batch_keys = keys[i:i+batch_size]
            batch_values = values[i:i+batch_size]
            
            # Extract keywords
            batch_results = self.extract_keywords_batch(batch_values)
            
            # Store results
            for key, result in zip(batch_keys, batch_results):
                result_data[key] = result
        
        # Save results
        print(f"Saving results to: {output_file}")
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(result_data, f, ensure_ascii=False, indent=2)
        
        print("Processing completed!")
        return result_data

def main():
    parser = argparse.ArgumentParser(description="Extract keywords using vLLM")
    parser.add_argument("--input", "-i", 
                       default="../data/tag_id_to_text_mapping_ds-target-split.json",
                       help="Input JSON file path")
    parser.add_argument("--output", "-o", 
                       default="../data/extracted_keywords_ds-target-split.json",
                       help="Output JSON file path")
    parser.add_argument("--model", "-m",
                       default="Qwen/Qwen2.5-7B-Instruct",
                       help="Model name")
    parser.add_argument("--batch-size", "-b",
                       type=int, default=32,
                       help="Batch processing size (4-card A100 recommended 32-64)")
    parser.add_argument("--tensor-parallel-size", "-t",
                       type=int, default=4,
                       help="Tensor parallel size (number of GPU cards)")
    
    args = parser.parse_args()
    
    # Create keyword extractor
    extractor = KeywordExtractor(
        model_name=args.model,
        tensor_parallel_size=args.tensor_parallel_size
    )
    
    # Process file
    extractor.process_json_file(
        input_file=args.input,
        output_file=args.output,
        batch_size=args.batch_size
    )

if __name__ == "__main__":
    main()